const Data = [
    {
      id: 1,
      img: "products/2a.webp",
      title: "One Plus 7T",
      price: "45,000",
      brand: "One Plus",
      condition:'10/10',
      ram:'8GB',
      display:'6.5"(1080x2400 pixels)',
      storage:'128GB, Snapdragon 855+',
      battery:'3800mAh Li-Po',
      colors:'Glacier Blue',
      star1: <i class="fas fa-star"></i>,
      star2: <i class="fas fa-star"></i>,
      star3: <i class="fas fa-star"></i>,
      star4: <i class="fas fa-star"></i>,
      star5: <i class="fas fa-star-half-alt"></i>,
      link: "https://www.olx.com.pk/profile/6b9f86ba-34f9-4c29-82ff-3f39ec1006a5",
    },
    {
      id: 2,
      img: "products/7plus.jpg",
      title: "Iphone 7 Plus",
      price: "43,000",
      brand: "Iphone",
      condition:'10/10',
      ram:'3GB',
      display:'5.5"(1080x1920 pixels)',
      storage:'128GB, Apple A10 Fusion',
      battery:'2900mAh Li-lon',
      colors:'Pure Black',
      star1: <i class="fas fa-star"></i>,
      star2: <i class="fas fa-star"></i>,
      star3: <i class="fas fa-star"></i>,
      star4: <i class="fas fa-star"></i>,
      star5: <i class="fas fa-star"></i>,
      link: "https://www.olx.com.pk/profile/6b9f86ba-34f9-4c29-82ff-3f39ec1006a5",
    },
    {
      id: 3,
      img: "products/google.jpg",
      title: "Google Pixel 3",
      price: "19,000",
      brand: "Google Pixel",
      condition:'10/10',
      ram:'4GB',
      display:'5.5"(1080x2160 pixels)',
      storage:'64GB, Snapdragon 845+',
      battery:'2915mAh Li-Po',
      colors:'Clearly White',
      star1: <i class="fas fa-star"></i>,
      star2: <i class="fas fa-star"></i>,
      star3: <i class="fas fa-star"></i>,
      star4: <i class="fas fa-star"></i>,
      star5: <i class="fas fa-star-half-alt"></i>,
      link: "https://www.olx.com.pk/profile/6b9f86ba-34f9-4c29-82ff-3f39ec1006a5",
    },
    {
      id: 4,
      img: "products/aquas.jpg",
      title: "Aquas R2 ",
      price: "17,000",
      brand: "Aquas japan",
      condition:'10/10',
      ram:'4GB',
      display:'5.2"(1080x2280 pixels)',
      storage:'64GB, Snapdragon 845',
      battery:'2500mAh Li-lon',
      colors:'Pure black',
      star1: <i class="fas fa-star"></i>,
      star2: <i class="fas fa-star"></i>,
      star3: <i class="fas fa-star"></i>,
      star4: <i class="fas fa-star-half-alt"></i>,
      star5: <i class="far fa-star"></i>,
      link: "https://www.olx.com.pk/profile/6b9f86ba-34f9-4c29-82ff-3f39ec1006a5",
    },
  ];
  export default Data;
  