const Data = [
  
    {
      id: 4,
      img: "products/xr.jpg",
      title: "Iphone XR",
      price: "65,000",
      brand: "Apple",
      condition:'10/10',
      ram:'3GB',
      category:'iphones',
      display:'6.1"(828x1792 pixels)',
      storage:'64GB, Apple A12 Bionic',
      battery:'2942mAh Li-lon iOS 15',
      colors:'black, Blue,Red',
      star1: <i class="fas fa-star"></i>,
      star2: <i class="fas fa-star"></i>,
      star3: <i class="fas fa-star"></i>,
      star4: <i class="fas fa-star"></i>,
      star5: <i class="fas fa-star"></i>,
      link: "https://www.olx.com.pk/profile/6b9f86ba-34f9-4c29-82ff-3f39ec1006a5",
    },
    {
      id: 5,
      img: "products/x.jpg",
      title: "Iphone X",
      price: "48,000",
      brand: "Apple",
      condition:'10/10',
      ram:'3GB',
      category:'iphones',
      display:'5.8"(1125x2436 pixels)',
      storage:'64GB, Apple A11 Bionic',
      battery:'2716mAh Li-lon',
      colors:'Light Balck',
      star1: <i class="fas fa-star"></i>,
      star2: <i class="fas fa-star"></i>,
      star3: <i class="fas fa-star"></i>,
      star4: <i class="fas fa-star"></i>,
      star5: <i class="fas fa-star-half-alt"></i>,
      link: "https://www.olx.com.pk/profile/6b9f86ba-34f9-4c29-82ff-3f39ec1006a5",
    },
    {
      id: 6,
      img: "products/iphone8plus.jpg",
      title: "Iphone 8 Plus",
      price: "58,000",
      brand: "Apple",
      condition:'10/10',
      ram:'3GB',
      category:'iphones',
      display:'5.5"(1080x1920 pixels)',
      storage:'64GB, Apple A11 Bionic',
      battery:'2691mAh Li-lon',
      colors:'Golden',
      star1: <i class="fas fa-star"></i>,
      star2: <i class="fas fa-star"></i>,
      star3: <i class="fas fa-star"></i>,
      star4: <i class="fas fa-star"></i>,
      star5: <i class="far fa-star"></i>,
      link: "https://www.olx.com.pk/profile/6b9f86ba-34f9-4c29-82ff-3f39ec1006a5",
    },
    {
      id: 7,
      img: "products/iphone8.jpg",
      title: "Iphone 8",
      price: "50,000",
      brand: "Apple",
      condition:'10/10',
      ram:'2GB',
      category:'iphones',
      display:'4.7"(750x1334 pixels)',
      storage:'64GB, Apple A11 Bionic',
      battery:'1821mAh Li-lon',
      colors:'Black,White',
      star1: <i class="fas fa-star"></i>,
      star2: <i class="fas fa-star"></i>,
      star3: <i class="fas fa-star"></i>,
      star4: <i class="fas fa-star"></i>,
      star5: <i class="far fa-star"></i>,
      link: "https://www.olx.com.pk/profile/6b9f86ba-34f9-4c29-82ff-3f39ec1006a5",
    },
    {
      id: 8,
      img: "products/iphone7plus.jpg",
      title: "Iphone 7 Plus",
      price: "43,000",
      brand: "Apple",
      condition:'10/10',
      ram:'3GB',
      category:'iphones',
      display:'5.5"(1080x1920 pixels)',
      storage:'128GB, Apple A10 Fusion',
      battery:'2900mAh Li-lon',
      colors:'Pure Black',
      star1: <i class="fas fa-star"></i>,
      star2: <i class="fas fa-star"></i>,
      star3: <i class="fas fa-star"></i>,
      star4: <i class="fas fa-star"></i>,
      star5: <i class="far fa-star"></i>,
      link: "https://www.olx.com.pk/profile/6b9f86ba-34f9-4c29-82ff-3f39ec1006a5",
    },
    {
      id: 9,
      img: "products/iphone7.jpg",
      title: "Iphone 7",
      price: "37,000",
      brand: "Apple",
      condition:'10/10',
      ram:'2GB',
      category:'iphones',
      display:'4.7"(750x1334 pixels)',
      storage:'128GB, Apple A10 Fusion',
      battery:'1960mAh Li-lon',
      colors:' Ross Gold',
      star1: <i class="fas fa-star"></i>,
      star2: <i class="fas fa-star"></i>,
      star3: <i class="fas fa-star"></i>,
      star4: <i class="fas fa-star"></i>,
      star5: <i class="fas fa-star"></i>,
      link: "https://www.olx.com.pk/profile/6b9f86ba-34f9-4c29-82ff-3f39ec1006a5",
    },
    {
      id: 10,
      img: "products/iphone 6s.jpg",
      title: "Iphone 6s",
      price: "28,0000",
      brand: "One Plus",
      condition:'10/10',
      ram:'2GB',
      category:'iphones',
      display:'4.7"(750x1334 pixels)',
      storage:'16/32GB, Apple A9',
      battery:'1715mAh Li-lon',
      colors:'Ross Gold',
      star1: <i class="fas fa-star"></i>,
      star2: <i class="fas fa-star"></i>,
      star3: <i class="fas fa-star"></i>,
      star4: <i class="fas fa-star"></i>,
      star5: <i class="far fa-star"></i>,
      link: "https://www.olx.com.pk/profile/6b9f86ba-34f9-4c29-82ff-3f39ec1006a5",
    },
    {
      id: 11,
      img: "products/aquas.jpg",
      title: "Aquas R2",
      price: "17,000",
      brand: "Aquas japan",
      condition:'10/10',
      ram:'4GB',
      category:'aquas',
      display:'5.2"(1080x2280 pixels)',
      storage:'64GB, Snapdragon 845',
      battery:'2500mAh Li-lon',
      colors:'Pure Black',
      star1: <i class="fas fa-star"></i>,
      star2: <i class="fas fa-star"></i>,
      star3: <i class="fas fa-star"></i>,
      star4: <i class="fas fa-star"></i>,
      star5: <i class="fas fa-star-half-alt"></i>,
      link: "https://www.olx.com.pk/profile/6b9f86ba-34f9-4c29-82ff-3f39ec1006a5",
    },
    {
      id: 12,
      img: "products/ar2compact.jpg",
      title: "Aquas Ar2 compact",
      price: "20,000",
      brand: "Aquas japan",
      condition:'10/10',
      ram:'4GB',
      category:'aquas',
      display:'5.5"(1080x2400 pixels)',
      storage:'64GB, Snapdragon 855',
      battery:'4200mAh Li-lon',
      colors:'Light Green',
      star1: <i class="fas fa-star"></i>,
      star2: <i class="fas fa-star"></i>,
      star3: <i class="fas fa-star"></i>,
      star4: <i class="far fa-star"></i>,
      star5: <i class="far fa-star"></i>,
      link: "https://www.olx.com.pk/profile/6b9f86ba-34f9-4c29-82ff-3f39ec1006a5",
    },
    {
      id: 11,
      img: "products/gp3xl.jpg",
      title: "Google Pixel 3XL",
      price: "29,000",
      brand: "Google Pixel",
      condition:'10/10',
      ram:'4/6GB',
      category:'googlepixel',
      display:'6.3"(1440x2960 pixels)',
      storage:'64/128GB, Snapdragon 845',
      battery:'3430mAh Li-Po',
      colors:'Royal Black',
      star1: <i class="fas fa-star"></i>,
      star2: <i class="fas fa-star"></i>,
      star3: <i class="fas fa-star"></i>,
      star4: <i class="fas fa-star"></i>,
      star5: <i class="fas fa-star"></i>,
      link: "https://www.olx.com.pk/profile/6b9f86ba-34f9-4c29-82ff-3f39ec1006a5",
    },
    {
      id: 12,
      img: "products/gp3.jpg",
      title: "Google Pixel 3",
      price: "19,000",
      brand: "One Plus",
      condition:'10/10',
      ram:'4GB',
      category:'googlepixel',
      display:'5.5"(1080x2160 pixels)',
      storage:'128GB, Snapdragon 845',
      battery:'2915mAh Li-Po',
      colors:'Black',
      star1: <i class="fas fa-star"></i>,
      star2: <i class="fas fa-star"></i>,
      star3: <i class="fas fa-star"></i>,
      star4: <i class="fas fa-star"></i>,
      star5: <i class="fas fa-star-half-alt"></i>,
      link: "https://www.olx.com.pk/profile/6b9f86ba-34f9-4c29-82ff-3f39ec1006a5",
    },
    {
      id: 13,
      img: "products/snote105g.jpg",
      title: "Samsung Note 10 5G",
      price: "62,000",
      brand: "Smasung",
      condition:'10/10',
      ram:'8GB',
      category:'samsung',
      display:'6.3"(1080 x 2280 Pixels)',
      storage:'256GB, 	Exynos 9825 7nm ',
      battery:'3800mAh Li-Po',
      colors:'Aura White',
      star1: <i class="fas fa-star"></i>,
      star2: <i class="fas fa-star"></i>,
      star3: <i class="fas fa-star"></i>,
      star4: <i class="fas fa-star"></i>,
      star5: <i class="fas fa-star"></i>,
      link: "https://www.olx.com.pk/profile/6b9f86ba-34f9-4c29-82ff-3f39ec1006a5",
    },
    {
      id: 14,
      img: "products/sgs105g.jpg",
      title: "Samsung S10 5G",
      price: "48,000",
      brand: "Samsung",
      condition:'10/10',
      ram:'8GB',
      category:'samsung',
      display:'6.5"(1080x2400 pixels)',
      storage:'128GB, Snapdragon 855+',
      battery:'4200mAh Li-Po',
      colors:' Royal Blue',
      star1: <i class="fas fa-star"></i>,
      star2: <i class="fas fa-star"></i>,
      star3: <i class="fas fa-star"></i>,
      star4: <i class="far fa-star"></i>,
      star5: <i class="far fa-star"></i>,
      link: "https://www.olx.com.pk/profile/6b9f86ba-34f9-4c29-82ff-3f39ec1006a5",
    },
    {
      id: 15,
      img: "products/sgs10lite.jpg",
      title: "Samsung S10 Lite",
      price: "40,000",
      brand: "Samsung",
      condition:'10/10',
      ram:'6/8GB',
      category:'samsung',
      display:'6.7"(1080 x 2400 Pixels)',
      storage:'128GB, 	Qualcomm SM8150 Snapdragon 855 (7 nm)',
      battery:'4500mAh Li-Po',
      colors:'Glacier Blue',
      star1: <i class="fas fa-star"></i>,
      star2: <i class="fas fa-star"></i>,
      star3: <i class="fas fa-star"></i>,
      star4: <i class="fas fa-star"></i>,
      star5: <i class="far fa-star"></i>,
      link: "https://www.olx.com.pk/profile/6b9f86ba-34f9-4c29-82ff-3f39ec1006a5",
    },
  ];
  export default Data;
  