const Data = [
  {
    id: 1,
    img: "products/8t.jpg",
    title: "One Plus 8T",
    price: "87,000",
    brand: "One Plus",
    condition:'BOX PACK',
    ram:'8/12GB',
    category:'oneplus8',
    display:'6.55"(1080x2400 pixels)',
    storage:'128/256GB, Snapdragon 865+',
    battery:'4500mAh Li-Po',
    colors:'Lunar Silver',
    star1: <i class="fas fa-star"></i>,
    star2: <i class="fas fa-star"></i>,
    star3: <i class="fas fa-star"></i>,
    star4: <i class="fas fa-star"></i>,
    star5: <i class="fas fa-star"></i>,
    link: "https://www.olx.com.pk/profile/6b9f86ba-34f9-4c29-82ff-3f39ec1006a5",
  },
  {
    id: 2,
    img: "products/8pro.jpg",
    title: "One Plus 8 pro",
    price: "112,000",
    brand: "One Plus",
    condition:'BOX PACK',
    ram:'8GB',
    category:'oneplus8',
    display:'6.78"(1080x2400 pixels)',
    storage:'128GB, Snapdragon 865',
    battery:'4510mAh Li-Po',
    colors:'Ultramarine Blue',
    star1: <i class="fas fa-star"></i>,
    star2: <i class="fas fa-star"></i>,
    star3: <i class="fas fa-star"></i>,
    star4: <i class="fas fa-star"></i>,
    star5: <i class="fas fa-star-half-alt"></i>,
    link: "https://www.olx.com.pk/profile/6b9f86ba-34f9-4c29-82ff-3f39ec1006a5",
  },
  {
    id: 3,
    img: "products/8.jpg",
    title: "One Plus 8",
    price: "60,000",
    brand: "One Plus",
    condition:'10/10',
    ram:'8GB',
    category:'oneplus8',
    display:'6.55"(1080x2400 pixels)',
    storage:'128GB, Snapdragon 865',
    battery:'4300mAh Li-Po',
    colors:'Interstellar Glow',
    star1: <i class="fas fa-star"></i>,
    star2: <i class="fas fa-star"></i>,
    star3: <i class="fas fa-star"></i>,
    star4: <i class="fas fa-star"></i>,
    star5: <i class="fas fa-star"></i>,
    link: "https://www.olx.com.pk/profile/6b9f86ba-34f9-4c29-82ff-3f39ec1006a5",
  },
  {
    id: 4,
    img: "products/7tpro.jpg",
    title: "One Plus 7T pro",
    price: "57,000",
    brand: "One Plus",
    condition:'10/10',
    ram:'8GB',
    category:'oneplus7t',
    display:'6.67"(1440x3120 pixels)',
    storage:'128GB, Snapdragon 855+',
    battery:'4085mAh Li-Po',
    colors:'Glacier Blue',
    star1: <i class="fas fa-star"></i>,
    star2: <i class="fas fa-star"></i>,
    star3: <i class="fas fa-star"></i>,
    star4: <i class="fas fa-star"></i>,
    star5: <i class="fas fa-star-half-alt"></i>,
    link: "https://www.olx.com.pk/profile/6b9f86ba-34f9-4c29-82ff-3f39ec1006a5",
  },
  {
    id: 5,
    img: "products/7tm.jpg",
    title: "One Plus 7T pro (mechlaran addittion)",
    price: "58,000",
    brand: "One Plus",
    condition:'10/10',
    ram:'12GB',
    category:'oneplus7t',
    display:'6.67"(1440x3120 pixels)',
    storage:'128/256GB, Snapdragon 855+',
    battery:'4085mAh Li-Po',
    colors:'Papaya Orange',
    star1: <i class="fas fa-star"></i>,
    star2: <i class="fas fa-star"></i>,
    star3: <i class="fas fa-star"></i>,
    star4: <i class="fas fa-star"></i>,
    star5: <i class="far fa-star"></i>,
    link: "https://www.olx.com.pk/profile/6b9f86ba-34f9-4c29-82ff-3f39ec1006a5",
  },
  {
    id: 6,
    img: "products/7t.jpg",
    title: "One Plus 7T",
    price: "45,000",
    brand: "One Plus",
    condition:'10/10',
    ram:'8GB',
    category:'oneplus7t',
    display:'6.5"(1080x2400 pixels)',
    storage:'128GB, Snapdragon 855+',
    battery:'3800mAh Li-Po',
    colors:'Glacier Blue',
    star1: <i class="fas fa-star"></i>,
    star2: <i class="fas fa-star"></i>,
    star3: <i class="fas fa-star"></i>,
    star4: <i class="fas fa-star"></i>,
    star5: <i class="fas fa-star"></i>,
    link: "https://www.olx.com.pk/profile/6b9f86ba-34f9-4c29-82ff-3f39ec1006a5",
  },
  {
    id: 7,
    img: "products/7pro.jpg",
    title: "One Plus 7pro",
    price: "52,000",
    brand: "One Plus",
    condition:'10/10',
    ram:'8GB',
    category:'oneplus7t',
    display:'6.67"(1440x3120 pixels)',
    storage:'128GB, Snapdragon 855',
    battery:'4000mAh Li-Po',
    colors:'Glacier Blue',
    star1: <i class="fas fa-star"></i>,
    star2: <i class="fas fa-star"></i>,
    star3: <i class="fas fa-star"></i>,
    star4: <i class="fas fa-star-half-alt"></i>,
    star5: <i class="far fa-star"></i>,
    link: "https://www.olx.com.pk/profile/6b9f86ba-34f9-4c29-82ff-3f39ec1006a5",
  },
  {
    id: 8,
    img: "products/7.jpg",
    title: "One Plus 7",
    price: "37,000",
    brand: "One Plus",
    condition:'10/10',
    ram:'8GB',
    category:'oneplus7t',
    display:'6.41"(1080x2340 pixels)',
    storage:'128GB, Snapdragon 855',
    battery:'3700mAh Li-Po',
    colors:'Light Black',
    star1: <i class="fas fa-star"></i>,
    star2: <i class="fas fa-star"></i>,
    star3: <i class="fas fa-star"></i>,
    star4: <i class="fas fa-star"></i>,
    star5: <i class="far fa-star"></i>,
    link: "https://www.olx.com.pk/profile/6b9f86ba-34f9-4c29-82ff-3f39ec1006a5",
  },
  {
    id: 9,
    img: "products/6tm.jpg",
    title: "One Plus 6T(mechlaran addittion)",
    price: "42,000",
    brand: "One Plus",
    condition:'10/10',
    ram:'10GB',
    category:'oneplus6t',
    display:'6.41"(1080x2400 pixels)',
    storage:'256GB, Snapdragon 845',
    battery:'3700mAh Li-Po',
    colors:'Glacier Blue',
    star1: <i class="fas fa-star"></i>,
    star2: <i class="fas fa-star"></i>,
    star3: <i class="fas fa-star"></i>,
    star4: <i class="fas fa-star"></i>,
    star5: <i class="fas fa-star"></i>,
    link: "https://www.olx.com.pk/profile/6b9f86ba-34f9-4c29-82ff-3f39ec1006a5",
  },
  {
    id: 10,
    img: "products/6t.jpg",
    title: "One Plus 6T",
    price: "35,000",
    brand: "One Plus",
    condition:'10/10',
    ram:'8GB',
    category:'oneplus6t',
    display:'6.41"(1080x2340 pixels)',
    storage:'128GB, Snapdragon 855+',
    battery:'3800mAh Li-Po',
    colors:'Glacier Blue',
    star1: <i class="fas fa-star"></i>,
    star2: <i class="fas fa-star"></i>,
    star3: <i class="fas fa-star"></i>,
    star4: <i class="fas fa-star"></i>,
    star5: <i class="fas fa-star-half-alt"></i>,
    link: "https://www.olx.com.pk/profile/6b9f86ba-34f9-4c29-82ff-3f39ec1006a5",
  },
  {
    id: 11,
    img: "products/6.jpg",
    title: "One Plus 6",
    price: "30,000",
    brand: "One Plus",
    condition:'10/10',
    ram:'6GB',
    category:'oneplus6t',
    display:'6.28"(1080x2280 pixels)',
    storage:'128GB, Snapdragon 845',
    battery:'3300mAh Li-Po',
    colors:'Amber Red',
    star1: <i class="fas fa-star"></i>,
    star2: <i class="fas fa-star"></i>,
    star3: <i class="fas fa-star"></i>,
    star4: <i class="fas fa-star"></i>,
    star5: <i class="fas fa-star"></i>,
    link: "https://www.olx.com.pk/profile/6b9f86ba-34f9-4c29-82ff-3f39ec1006a5",
  },
  {
    id: 12,
    img: "products/9 pro.jpg",
    title: "One Plus 9 Pr0",
    price: "145,000",
    brand: "One Plus",
    condition:'BOX PACK',
    ram:'12GB',
    category:'oneplus9',
    display:'6.7"(1440x3216 pixels)',
    storage:'256GB, Snapdragon 888 5G',
    battery:'4500mAh ',
    colors:'Stellar Black',
    star1: <i class="fas fa-star"></i>,
    star2: <i class="fas fa-star"></i>,
    star3: <i class="fas fa-star"></i>,
    star4: <i class="fas fa-star"></i>,
    star5: <i class="fas fa-star"></i>,
    link: "https://www.olx.com.pk/profile/6b9f86ba-34f9-4c29-82ff-3f39ec1006a5",
  }
];
export default Data;
